insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1001, '2024-05-19', 'bjedrych0@hc360.com', 'Bourke Jedrych', 'CUSTOMER');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1002, '2024-03-30', 'htreweke1@instagram.com', 'Hal Treweke', 'AFFILIATE');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1003, '2024-01-26', 'ccolleton2@bravesites.com', 'Clayson Colleton', 'AFFILIATE');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1004, '2021-11-28', 'jkembery3@bloglovin.com', 'Job Kembery', 'CUSTOMER');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1005, '2018-11-06', 'mtrueman4@topsy.com', 'Mollee Trueman', 'CUSTOMER');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1006, '2024-03-07', 'btricker5@ustream.tv', 'Bailie Tricker', 'EMPLOYEE');
insert into USERS (USER_ID, CREATED_DATE, EMAIL_ID, NAME, USER_TYPE) values (1007, '2017-03-28', 'tcristofolo6@miibeian.gov.cn', 'Thayne Cristofolo', 'EMPLOYEE');

insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (101, 'Mango', 'GROCERY', 45.9);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (102, 'Milk', 'DAIRY', 23.9);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (103, 'Fridge', 'ELECTRONICS', 895.2);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (104, 'Salt', 'GROCERY', 20.0);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (105, 'Wall decor', 'DECOR', 300.5);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (106, 'Microwave', 'ELECTRONICS', 15000.0);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (107, 'Sugar', 'GROCERY', 40.6);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (108, 'Sticker', 'DECOR', 70.5);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (109, 'Fridge 2', 'ELECTRONICS', 9895.2);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (110, 'Banana', 'GROCERY', 145.9);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (111, 'Bat', 'MISC', 2000.0);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (112, 'Fridge 3', 'ELECTRONICS', 16895.2);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (113, 'Biscuit', 'GROCERY', 65.0);
insert into PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, PRICE) values (114, 'Ball', 'MISC', 176.0);

insert into DISCOUNT_RULES (DISCOUNT_RULE_ID, DISCOUNT_AMT, DISCOUNT_PERCENTAGE, IS_DISCOUNT, RETENTION_YEARS, TYPE_KEY, TYPE_VALUE )
					values (101, 0, 30, true, 0, 'USERTYPE', 'EMPLOYEE');
insert into DISCOUNT_RULES (DISCOUNT_RULE_ID, DISCOUNT_AMT, DISCOUNT_PERCENTAGE, IS_DISCOUNT, RETENTION_YEARS, TYPE_KEY, TYPE_VALUE )
					values (102, 0, 10, true, 0, 'USERTYPE', 'AFFILIATE');
insert into DISCOUNT_RULES (DISCOUNT_RULE_ID, DISCOUNT_AMT, DISCOUNT_PERCENTAGE, IS_DISCOUNT, RETENTION_YEARS, TYPE_KEY, TYPE_VALUE )
					values (103, 0, 5, true, 2, 'USERTYPE', 'CUSTOMER');
insert into DISCOUNT_RULES (DISCOUNT_RULE_ID, DISCOUNT_AMT, DISCOUNT_PERCENTAGE, IS_DISCOUNT, RETENTION_YEARS, TYPE_KEY, TYPE_VALUE )
					values (104, 0, 0, false, 0, 'PRODUCTTYPE', 'GROCERY');
insert into DISCOUNT_RULES (DISCOUNT_RULE_ID, DISCOUNT_AMT, DISCOUNT_PERCENTAGE, IS_DISCOUNT, RETENTION_YEARS, TYPE_KEY, TYPE_VALUE )
					values (105, 5, 0, true, 0, 'AMOUNT', '100');